### ISSUE TITLE
Unknown debugger type "No engine"

### ISSUE THREAD

**Issue by arthursw** [NAlphaDev/Unreal-Qt-project-generator#1]
I successfully created a Qt project, I can compile and run it in release mode, but in debug mode I get:
"Unknown debugger type "No engine". Unable to create a debugger engine of the type "No engine" "

![unknowndebugger](https://cloud.githubusercontent.com/assets/1814799/9700005/3820aa7c-53f5-11e5-9a63-5d44fe8529c3.png)

Anyway: Thanks a lot for this amazing tool !!!

**Comment by arthursw** [comment]
I realized that I did not select any debugger in my kit, so I selected GDB but now it says:
"The selected build of GDB does not support python scripting. It cannot be used in QtCreator."

**Comment by nibau** [comment]
I apologize for not making this clear on the GitHub page.
For debugging support you have to use CDB (Microsoft Debugger) instead of GDB, because your code and Unreal Engine 4 are compiled with MSVC compiler.

For CDB installation and configuration instructions (and a guide how to achieve the best possible experience with QtCreator and Unreal Engine 4), please take a look at <a href=https://forums.unrealengine.com/showthread.php?59458-TOOL-Tut-WIN-Unreal-Qt-Creator-Project-Generator-(v0-1-Beta)>this</a> post.

And thank you, I'm happy to hear you like the tool:)
